version: '3.4'

services:
  portainer:
    restart: always
    image: portainer/portainer
    container_name: portainer
    ports:
      - "9000:9000"
    logging:
      options:
        max-size: 50m
    command: -H unix:///var/run/docker.sock
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
      - type: volume
        source: portainer_data
        target: /data
    dns: 10.128.255.6
    dns_search: lnls-sirius.com.br

volumes:
  portainer_data:
